before_install:
  - gem install bundler
language: ruby
rvm:
  - 1.9.3
  - 1.8.7
script: 
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
