common: &common
  use_ssl: true
  authentication_method: database_authenticatable
  caller_id: "+14248886496"
  machine_detection_wait_time: 15   # Should not be less than 10
  default_retry: 2
  admin_email: admin@myhost.com
  base_url: http://ec2-184-73-63-238.compute-1.amazonaws.com:3000/
  twilio_conf_file: config/twilio.yml    # Where you store your twilio account sid and secret token
  whitepages_conf_file: config/whitepages.yml
  business_hours: ["8:00", "18:00"]
  require_sms_gateway: true
  require_phone_number: true
  oncall_assignments_gen:
    from_now: 4 # generate oncalls for this number of weeks from today
  events_retention: 2 # how long to keep old events for
  
  error_alerts:
    thresh_hold: 60 # minutes. Don't send alerts if one already sent within this period
    oncall_updates:
      email: true
      phone: true
      sms: true

development: &development
  <<: *common
  authentication_method: database_authenticatable
  use_ssl: false

production:
  authentication_method: ldap_authenticatable
  <<: *common

test:
  <<: *development
