common: &common
  use_ssl: true
  authentication_method: database_authenticatable
  caller_id: "+16198003327"
  machine_detection_wait_time: 15   # Should not be less than 10
  default_retry: 2
  admin_email: unix-sa@eharmony.com

development:
  <<: *common
  authentication_method: database_authenticatable
  use_ssl: false

production:
  authentication_method: ldap_authenticatable
  <<: *common
